server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3300/shop
    username: root
    password: root
    driveClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
